### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by peterdotjs** [raptorjs/atom-language-marko#1]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `language-marko` package
```
Package.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:434:9)
Package.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app/src/package.js:445:32)
```
Deprecation warning appearing on v0.182.0

**Comment by patrick-steele-idem** [comment]
I haven't noticed the warning, bit I'll go ahead and make the change. Thanks for letting me know.
